package routes

import (
	"github.com/gbsto/daisy/api"
	"github.com/gbsto/daisy/web/cmd"
	"github.com/gbsto/daisy/web/middleware"
	"github.com/gbsto/daisy/web/passkey"
	"github.com/gofiber/fiber/v2"
)

func Routes(app *fiber.App) {
	app.Get("/", cmd.GetIndex)
	app.Get("/tour.html", cmd.GetTour)
	app.Get("/index.html", cmd.GetIndex)
	app.Get("/registration.html", cmd.GetRegistration)
	app.Get("/login.html", cmd.GetLogin)
	app.Get("/logout.html", middleware.CheckToken, cmd.GetLogout)
	app.Get("/about.html", middleware.CheckToken, cmd.GetAbout)
	app.Get("/banned.html", cmd.GetBanned)
	app.Get("/captcha.html", cmd.GetCaptcha)
	app.Get("/home.html", middleware.CheckToken, cmd.GetHome)
	app.Post("/home", middleware.CheckToken, cmd.PostHome)
	app.Get("/softwares.html", middleware.CheckToken, cmd.GetSoftwares)
	app.Post("softwares", middleware.CheckToken, cmd.PostSoftwares)
	app.Get("/software.html", middleware.CheckToken, cmd.GetSoftware)
	app.Post("/software", middleware.CheckToken, cmd.PostSoftware)
	app.Get("/profiles.html", middleware.CheckToken, cmd.GetProfiles)
	app.Post("/profiles", middleware.CheckToken, cmd.PostProfiles)
	app.Get("/profile.html", middleware.CheckToken, cmd.GetProfile)
	app.Post("/profile", middleware.CheckToken, cmd.PostProfile)
	app.Get("/device.html", middleware.CheckToken, cmd.GetDevice)
	app.Post("/device", middleware.CheckToken, cmd.PostDevice)
	app.Post("/upload", middleware.CheckToken, cmd.UploadImage)
	app.Get("/wizard.html", middleware.CheckToken, cmd.GetWizard)
	app.Post("/wizard", middleware.CheckToken, cmd.PostWizard)
	app.Get("/admin.html", middleware.CheckToken, cmd.GetAdmin)
	app.Post("/admin", middleware.CheckToken, cmd.PostAdmin)
	app.Get("/reports.html", middleware.CheckToken, cmd.GetReports)
	app.Post("/reports", middleware.CheckToken, cmd.PostReports)
	app.Get("/devices.html", middleware.CheckToken, cmd.GetDevices)
	app.Post("/devices", middleware.CheckToken, cmd.PostDevices)
	app.Post("/inventory", middleware.CheckToken, cmd.PostInventory)
	app.Post("/api/audit", api.PostSoftwareApi)
	app.Post("/api/passkey/requestCode", passkey.RequestCode)
	app.Post("/api/passkey/registerStart", passkey.BeginRegistration)
	app.Post("/api/passkey/registerFinish", passkey.FinishRegistration)
	app.Post("/api/passkey/loginStart", passkey.BeginLogin)
	app.Post("/api/passkey/loginFinish", passkey.FinishLogin)
	app.Get("/ticket.html", middleware.CheckToken, cmd.GetTicket)
	app.Post("/ticket", middleware.CheckToken, cmd.PostTicket)
	app.Get("/tickets.html", middleware.CheckToken, cmd.GetTickets)
	app.Post("/api/ping", api.PostPingApi)
	app.Post("/droplist", middleware.CheckToken, cmd.PostDroplist)
	app.Get("/control.html", middleware.CheckToken, cmd.GetControl)
	app.Post("/control", middleware.CheckToken, cmd.PostControl)
	app.Post("/api/backups", api.PostBackupsApi)
	app.Post("/preinstalled", middleware.CheckToken, cmd.PostPreInstalled)
	app.Post("/api/isaw", api.PostiSawApi)
	app.Post("/api/sighting", cmd.PostSightingApi)
	app.Post("/api/online", api.PostOnlineApi)
	app.Get("/online.html", middleware.CheckToken, cmd.GetOnline)
	app.Post("/online/getmac", middleware.CheckToken, cmd.PostOnlineGetMac)
	app.Post("/online/setmac", middleware.CheckToken, cmd.PostOnlineSetMac)
	app.Get("/history.html", middleware.CheckToken, cmd.GetHistory)
	app.Get("/network.html", middleware.CheckToken, cmd.GetNetwork)
	app.Get("/duplicates.html", middleware.CheckToken, cmd.GetDuplicates)
	app.Post("/duplicates", middleware.CheckToken, cmd.PostDuplicates)
	app.Post("/duplicatesjoin", middleware.CheckToken, cmd.PostDuplicatesJoin)
	app.Get("/correlation.html", middleware.CheckToken, cmd.GetCorrelation)
	app.Post("/correlation", middleware.CheckToken, cmd.PostCorrelation)
}
