package webserver

import (
	"github.com/gbsto/daisy/api"
	"github.com/gbsto/daisy/cmd"
	"github.com/gbsto/daisy/passkey"
	"github.com/gofiber/fiber/v2"
)

func routes(app *fiber.App) {
	app.Get("/", cmd.GetIndex)
	app.Get("/index.html", cmd.GetIndex)
	app.Get("/registration.html", cmd.GetRegistration)
	app.Get("/login.html", cmd.GetLogin)
	app.Get("/logout.html", checkToken, cmd.GetLogout)
	app.Get("/about.html", checkToken, cmd.GetAbout)
	app.Get("/banned.html", cmd.GetBanned)
	app.Get("/captcha.html", cmd.GetCaptcha)
	app.Get("/home.html", checkToken, cmd.GetHome)
	app.Post("/home", checkToken, cmd.PostHome)
	app.Get("/softwares.html", checkToken, cmd.GetSoftwares)
	app.Post("softwares", checkToken, cmd.PostSoftwares)
	app.Get("/software.html", checkToken, cmd.GetSoftware)
	app.Post("/software", checkToken, cmd.PostSoftware)
	app.Get("/profiles.html", checkToken, cmd.GetProfiles)
	app.Post("/profiles", checkToken, cmd.PostProfiles)
	app.Get("/profile.html", checkToken, cmd.GetProfile)
	app.Post("/profile", checkToken, cmd.PostProfile)
	app.Get("/device.html", checkToken, cmd.GetDevice)
	app.Post("/device", checkToken, cmd.PostDevice)
	app.Post("/upload", checkToken, cmd.UploadImage)
	app.Get("/wizard.html", checkToken, cmd.GetWizard)
	app.Post("/wizard", checkToken, cmd.PostWizard)
	app.Get("/admin.html", checkToken, cmd.GetAdmin)
	app.Post("/admin", checkToken, cmd.PostAdmin)
	app.Get("/reports.html", checkToken, cmd.GetReports)
	app.Post("/reports", checkToken, cmd.PostReports)
	app.Get("/devices.html", checkToken, cmd.GetDevices)
	app.Post("/devices", checkToken, cmd.PostDevices)
	app.Post("/inventory", checkToken, cmd.PostInventory)
	app.Post("/api/audit", api.PostSoftwareApi)
	app.Post("/api/passkey/requestCode", passkey.RequestCode)
	app.Post("/api/passkey/registerStart", passkey.BeginRegistration)
	app.Post("/api/passkey/registerFinish", passkey.FinishRegistration)
	app.Post("/api/passkey/loginStart", passkey.BeginLogin)
	app.Post("/api/passkey/loginFinish", passkey.FinishLogin)
	app.Get("/ticket.html", checkToken, cmd.GetTicket)
	app.Post("/ticket", checkToken, cmd.PostTicket)
	app.Get("/tickets.html", checkToken, cmd.GetTickets)
	app.Post("/api/ping", api.PostPingApi)
	app.Post("/droplist", checkToken, cmd.PostDroplist)
	app.Get("/control.html", checkToken, cmd.GetControl)
	app.Post("/control", checkToken, cmd.PostControl)
	app.Post("/api/backups", api.PostBackupsApi)
	app.Post("/preinstalled", checkToken, cmd.PostPreInstalled)
	app.Post("/api/isaw", api.PostiSawApi)
	app.Post("/api/sighting", cmd.PostSightingApi)
	app.Post("/api/online", api.PostOnlineApi)
	app.Get("/online.html", checkToken, cmd.GetOnline)
	app.Post("/online/getmac", checkToken, cmd.PostOnlineGetMac)
	app.Post("/online/setmac", checkToken, cmd.PostOnlineSetMac)
	app.Get("/history.html", checkToken, cmd.GetHistory)
	app.Get("/network.html", checkToken, cmd.GetNetwork)
	app.Get("/duplicates.html", checkToken, cmd.GetDuplicates)
	app.Post("/duplicates", checkToken, cmd.PostDuplicates)
	app.Post("/duplicatesjoin", checkToken, cmd.PostDuplicatesJoin)
	app.Get("/correlation.html", checkToken, cmd.GetCorrelation)
	app.Post("/correlation", checkToken, cmd.PostCorrelation)
}
